---
name: Build 2.5-bullseye-slim

on:
  pull_request:
  push:
    paths:
      - '2.5/**'
      - '.github/workflows/build-2.5.yml'
  schedule:
    - cron: '40 *,* * * *'
  workflow_dispatch:

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 2.5 && docker build -t docker-2.5 .

      - name: Run the built image.
        run: cd 2.5 && docker run --name test-centos6 -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro docker-2.5

  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 2.5/
          file: 2.5/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ github.repository }}:2.5
