---
name: Build 2.6-dev-alpine

on:
  pull_request:
  push:
    paths:
      - '2.6/alpine/**'
      - '.github/workflows/build-2.6-rc-alpine.yml'
  schedule:
    - cron: '30 8,12 * * *'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  # Test the image builds and works correctly.
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test building image.
        run: cd 2.6-rc && cd alpine && docker build -t haproxy-2.6-alpine .

      - name: Run the built image.
        run: docker run -i --rm --name haproxy-syntax-check haproxy-2.6-alpine haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg
        
      - name: Run the container. 
        run: docker run -d --name my-running-haproxy-2.6-alpine --sysctl net.ipv4.ip_unprivileged_port_start=0 haproxy-2.6-alpine
        
  # If on master branch, build and release image.
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image.
        uses: docker/build-push-action@v2
        with:
          context: 2.6-rc/alpine/
          file: 2.6-rc/alpine/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ github.repository }}:2.6-dev0-alpine, ${{ github.repository }}:2.6-dev-alpine
