# This is a basic workflow to help you get started with Actions

name: Version/Upgrade CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  version-check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
  
      - name: chmod versions.sh
        run: chmod +x versions.sh
        
      - name: Check Version
        run: ./versions.sh
  run-update:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      needs: version-check

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: actions/checkout@v2

        - name: chmod
          run: chmod +x versions.sh && chmod +x update.sh && chmod +x apply-templates.sh

        - name: Update version
          run: ./update.sh
        
        - uses: actions/checkout@v2

        - uses: actions/download-artifact@v2
          id: download
          with:
            name: 'my-artifact'
            path: test

        - name: 'Echo download path'
          run: echo ${{steps.download.outputs.download-path}}
