name: Verify Templating

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: 'false'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  apply-templates:
    name: Check For Uncomitted Changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Apply Templates
        run: ./apply-templates.sh
      - name: Check Git Status
        run: |
          status="$(git status --short)"
          [ -z "$status" ]
